import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import { SteamGraphs } from '../components/steam-graphs'
import styles from '../styles/Home.module.css'

const getSteamGames = async (steamId: string) => {
  const response = await fetch(`/api/games/${steamId}`);
  const data = await response.json();
  return data;
}

export default function Home() {
  const [gameData, setGameData] = useState<any[]>([]);

  useEffect(() => {
    async function getData() {
      const gameRes = await getSteamGames("ABC") as any;
      setGameData(gameRes);
    }

    getData();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <SteamGraphs games={gameData} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
